### ISSUE TITLE
struggling to replicate

### ISSUE THREAD

**Issue by gcgbarbosa** [lifestrugglee/Privacy-Synthetic-Generation#1]
hi @lifestrugglee (love the username)

I am trying to replicate but I can't get past the pre-processing step.

I get stuck here:
https://github.com/mominbuet/GenerateEHRs/blob/7b1709ce70d30fc0281d8be7b7b67e89c42b653e/Utility/preprocess_original.py#L19C1-L19C38

I don't even know what I am missing. It looks like the mimic was supposed to come with a python file, mine did not :(

**Comment by lifestrugglee** [comment]
Hi @gcgbarbosa ,

It is from MIMIC III dataset, which you need to sign up on Physionet and download the entire dataset (https://physionet.org/content/mimiciii/1.4/).

Once you have the files, you can simply filter by 8 ICD9 code to extract the clinical notes.

**Comment by gcgbarbosa** [comment]
@lifestrugglee 

I have the dataset already. 

I need to replicate only the re-identification process from your paper.
If you have further instructions on how to do that, could you point me to it?

**Comment by lifestrugglee** [comment]
Yes, it is under this https://github.com/lifestrugglee/Privacy-Synthetic-Generation/tree/master/Pipeline/1_data_reidentification
